site_name: My Documentation
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Configuration: configuration.md
  - Advanced Features: advanced_features.md
  - Tutorials:
      - Tutorial 1: tutorials/tutorial1.md
      - Tutorial 2: tutorials/tutorial2.md
theme:
  name: material
